firFilterTest.elf:\
	firFilterTest.c \
	../inc/firFiltert_t.h

	gcc -g -O0 -o firFilterTest.elf firFilterTest.c -I../inc -I../extern/cSuite/cRollingWindow/inc -I../../cRollingWindow/inc
	
clean:
	rm *.elf